version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "0001-Select-the-current-user-to-authenticate-with-by-defa.patch",
    "0002-Auth-dialog-Make-the-label-wrap-at-70-chars.patch",
    "0003-Get-user-icon-from-accountsservice-instead-of-lookin.patch",
    "0004-Use-fresh-X11-timestamps-when-displaying-authenticat.patch",
]
SPDX-FileCopyrightText = "polkit-gnome contributors"
SPDX-License-Identifier = "LGPL-2.0-or-later"
