version = 1

[[annotations]]
path = [
    "PKGBUILD",
    ".SRCINFO",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "fix-doc-install.patch",
]
SPDX-FileCopyrightText = "zeromq contributors"
SPDX-License-Identifier = "MPL-2.0"
