---
version: 25.3-2
pkgbase:
  name: cloud-init
  pkgdesc: Cloud instance initialization
  pkgver: 25.3
  pkgrel: 2
  url: https://cloud-init.io
  arch:
    - any
  license:
    - GPL-3.0-only OR Apache-2.0
  checkdepends:
    - procps-ng
    - python-httpretty
    - python-passlib
    - python-pytest
    - python-pytest-mock
    - python-responses
  makedepends:
    - bash-completion
    - meson
    - udev
  depends:
    - bash
    - dhcp-client
    - openbsd-netcat
    - python
    - python-configobj
    - python-jinja
    - python-jsonpatch
    - python-jsonschema
    - python-netifaces
    - python-oauthlib
    - python-pyserial
    - python-pyyaml
    - python-requests
    - python-typing_extensions
    - sudo
  optdepends:
    - 'cloud-guest-utils: for growpart'
    - 'python-passlib: for Azure and BSD support'
    - 'python-urllib3: for LXD and Scaleway data sources'
  backup:
    - etc/cloud/cloud.cfg
    - etc/cloud/cloud.cfg.d/05_logging.cfg
  source:
    - https://github.com/canonical/cloud-init/archive/25.3/cloud-init-25.3.tar.gz
    - cloud-init-25.3-skip_openrc_check.patch
  sha512sums:
    - f881cac48fcb421fc07a435cd7a1acdf0b0c13aebf997af3100ecaca276e595a7ddaf778cff817c385a6b0103a36e326a5eeb8e281e8ef270ba2a4508d91168d
    - 64a49d8359fe7d51a5cf8449abab792b00d1bc910ab7928201af6f2fec87486a3658ee6d06e13c789b40618428bf209be56cd5c79dbdf3736f99ef85db08783c
  b2sums:
    - c49494ce91200f54a194554c19067f6533587fe3caebaf54e71d99548dcb956545ae709a775e09fad33a84702043b4e311626103c42b7d72190d1304bc45bdb3
    - b4805b7842bae79105d8963776f635067d4b0c9aab5a5c9ac311f6d754082923f2ab1faa9a867e4bcbc91923d0512d38f21527712a5b25b3ad431a189ca60c07
pkgname:
  - name: cloud-init
# generated with artixpkg 0.37.4-1-any
