version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "xdg-desktop-portal-lxqt-modal-dialog.patch",
    "xdg-desktop-portal-lxqt-wayland-parent.patch",
]
SPDX-FileCopyrightText = "xdg-desktop-portal-lxqt contributors"
SPDX-License-Identifier = "LGPL-2.1-or-later"
