version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "onionshare-loosen-cffi-version-bounds.patch",
    "onionshare-python-3.14-fix-multiprocessing.patch",
]
SPDX-FileCopyrightText = "onionshare contributors"
SPDX-License-Identifier = "GPL-3.0-or-later"
