version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
    "config",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "c23.patch"
]
SPDX-FileCopyrightText = "Linux Kernel contributors"
SPDX-License-Identifier = "GPL-2.0-only"

[[annotations]]
path = [
    "linux-hardened-v*-hardened*.patch"
]
SPDX-FileCopyrightText = "Linux Hardened Kernel contributors"
SPDX-License-Identifier = "GPL-2.0-only"
