version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "__init__.py",
    "fix-install.patch",
    "fix-missing-header.patch",
]
SPDX-FileCopyrightText = "lib3mf contributors"
SPDX-License-Identifier = "BSD-2-Clause"
