version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "transmageddon-autotools-fixes.patch",
    "transmageddon-gi-versions.patch",
    "transmageddon-no-appmenu.patch",
    "transmageddon-set-prgname.patch",
    "transmageddon-translatable.patch",
    "transmageddon-xml.etree.ElementTree.patch",
]
SPDX-FileCopyrightText = "transmageddon contributors"
SPDX-License-Identifier = "LGPL-2.1-or-later"
