version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "0001-xalan_libicu76.patch",
    "0002-cmake_min_version.patch",
    "0003-gcc_15_fixes.patch",
]
SPDX-FileCopyrightText = "xalan-c contributors"
SPDX-License-Identifier = "Apache-2.0"
