version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "fix-wrapper-preload-path.patch",
]
SPDX-FileCopyrightText = "bear contributors"
SPDX-License-Identifier = "GPL-3.0-or-later"
