version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "ranger-1.9.4-fix-ncurses-endwin-error-1.patch",
    "ranger-1.9.4-fix-ncurses-endwin-error-2.patch",
    "ranger-1.9.4-fix-ncurses-endwin-error-3.patch",
]
SPDX-FileCopyrightText = "ranger contributors"
SPDX-License-Identifier = "GPL-3.0-only"
