version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
    "*.conf",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "containers-common-0.48.0-init_path.patch",
    "containers-common-0.66.1-containers.conf-firewall-defaults.patch",
]
SPDX-FileCopyrightText = "containers-common contributors"
SPDX-License-Identifier = "Apache-2.0"
