---
version: 0.24.0-1
pkgbase:
  name: python-prometheus_client
  pkgdesc: Prometheus instrumentation library for Python applications
  pkgver: 0.24.0
  pkgrel: 1
  url: https://github.com/prometheus/client_python
  arch:
    - any
  license:
    - APACHE
  checkdepends:
    - python-twisted
    - python-pytest
    - python-aiohttp
    - python-snappy
    - python-asgiref
    - python-django
  makedepends:
    - python-setuptools
    - python-build
    - python-installer
    - python-wheel
  depends:
    - python
  optdepends:
    - 'python-snappy: snappy compression support'
    - 'python-aiohttp: aiohttp server support'
    - 'python-django: django exporter support'
  source:
    - client_python-0.24.0.tar.gz::https://github.com/prometheus/client_python/archive/v0.24.0.tar.gz
    - fix-test.patch
  sha512sums:
    - 3e4d5c2fd3263eacfd79c52c0e7b86d301fb053539cd99de5940cae4166d720495c399c45ba417c2602fac6ad283f52c9bc85028a0802f0e289bda5a6adb87bb
    - 4442ff79fc7dc57e500634156ebffbb81b3ac58ae5d1cfaa4e487c85bfcb3e1b73dfa2d9b29c9fd7a5ed4dcae48e79c4fe7139a0b94bf8b72f9691b368a2e57e
pkgname:
  - name: python-prometheus_client
# generated with artixpkg 0.37.4-1-any
