---
version: 13.1.0-1
pkgbase:
  name: ansible
  pkgdesc: Official assortment of Ansible collections
  pkgver: 13.1.0
  pkgrel: 1
  url: https://pypi.org/project/ansible/
  arch:
    - any
  license:
    - GPL-3.0-or-later
  makedepends:
    - python-build
    - python-installer
    - python-wheel
    - python-setuptools
  depends:
    - python
    - ansible-core
  optdepends:
    - 'python-argcomplete: shell completions'
    - 'python-pyopenssl: openssl modules'
    - 'python-dnspython: for dig lookup'
    - 'python-ovirt-engine-sdk: ovirt support'
    - 'python-boto3: aws_s3 module'
    - 'python-ldap: ldap support'
    - 'python-proxmoxer: proxmox modules'
    - 'python-openstacksdk: OpenStack module'
    - 'python-pynetbox: NetBox module'
    - 'python-ldap: LDAP modules'
    - 'python-kubernetes: Kubernetes modules'
    - 'python-keyring: Keyring module'
    - 'python-github3py: GitHub module'
    - 'python-lxc: LXC module'
    - 'python-fqdn: fqdn_valid module'
    - 'acme-tiny: openssl_certificate module'
  provides:
    - python-ansible_collections
  source:
    - https://pypi.python.org/packages/source/a/ansible/ansible-13.1.0.tar.gz
  sha512sums:
    - 2e7abd85b44d48ea756c65906811c9fa5519ce5d9ecaca71c718446a52dfc3dff97597d048f071ca820ea606ee2de670e8a0746717f95e2ce636db06273b3544
pkgname:
  - name: ansible
# generated with artixpkg 0.37.4-1-any
