---
version: 13.2.0-2.1
pkgbase:
  name: ansible
  pkgdesc: Official assortment of Ansible collections
  pkgver: 13.2.0
  pkgrel: 2.1
  url: https://pypi.org/project/ansible/
  arch:
    - any
  license:
    - GPL-3.0-or-later
  makedepends:
    - python-build
    - python-installer
    - python-wheel
    - python-setuptools
  depends:
    - python
    - ansible-core
  optdepends:
    - 'python-argcomplete: shell completions'
    - 'python-pyopenssl: openssl modules'
    - 'python-dnspython: for dig lookup'
    - 'python-ovirt-engine-sdk: ovirt support'
    - 'python-boto3: aws_s3 module'
    - 'python-proxmoxer: proxmox modules'
    - 'python-openstacksdk: OpenStack module'
    - 'python-pynetbox: NetBox module'
    - 'python-ldap: LDAP modules'
    - 'python-kubernetes: Kubernetes modules'
    - 'python-keyring: Keyring module'
    - 'python-github3py: GitHub module'
    - 'python-lxc: LXC module'
    - 'python-fqdn: fqdn_valid module'
    - 'acme-tiny: openssl_certificate module'
  provides:
    - python-ansible_collections
  source:
    - https://pypi.python.org/packages/source/a/ansible/ansible-13.2.0.tar.gz
  sha512sums:
    - 34a21653742729962cd784f6743ca37855089544a0b8029b2c1d48555df94b8cc68b0441a28950e2d0f074f0e1f4b1cd7bf693faa3d61aaaf716bfa6ed9a30a2
pkgname:
  - name: ansible
# generated with artixpkg 0.37.4-1-any
