---
version: 12.2.0-1
pkgbase:
  name: ansible
  pkgdesc: Official assortment of Ansible collections
  pkgver: 12.2.0
  pkgrel: 1
  url: https://pypi.org/project/ansible/
  arch:
    - any
  license:
    - GPL-3.0-or-later
  makedepends:
    - python-build
    - python-installer
    - python-wheel
    - python-setuptools
  depends:
    - python
    - ansible-core
  optdepends:
    - 'python-argcomplete: shell completions'
    - 'python-pyopenssl: openssl modules'
    - 'python-dnspython: for dig lookup'
    - 'python-ovirt-engine-sdk: ovirt support'
    - 'python-boto3: aws_s3 module'
    - 'python-ldap: ldap support'
    - 'python-proxmoxer: proxmox modules'
    - 'python-openstacksdk: OpenStack module'
    - 'python-pynetbox: NetBox module'
    - 'python-ldap: LDAP modules'
    - 'python-kubernetes: Kubernetes modules'
    - 'python-keyring: Keyring module'
    - 'python-github3py: GitHub module'
    - 'python-lxc: LXC module'
    - 'python-fqdn: fqdn_valid module'
    - 'acme-tiny: openssl_certificate module'
  provides:
    - python-ansible_collections
  source:
    - https://pypi.python.org/packages/source/a/ansible/ansible-12.2.0.tar.gz
  sha512sums:
    - 714e146a49385c3028f50b392c97759ea2660f2caa20a9baa7fae582e056b69b6cacf7af702adf6d77428532c58f45ec47815bd9979a4260eb9ab6762411b70f
pkgname:
  - name: ansible
# generated with artixpkg 0.37.4-1-any
