---
version: 13.0.0-1
pkgbase:
  name: ansible
  pkgdesc: Official assortment of Ansible collections
  pkgver: 13.0.0
  pkgrel: 1
  url: https://pypi.org/project/ansible/
  arch:
    - any
  license:
    - GPL-3.0-or-later
  makedepends:
    - python-build
    - python-installer
    - python-wheel
    - python-setuptools
  depends:
    - python
    - ansible-core
  optdepends:
    - 'python-argcomplete: shell completions'
    - 'python-pyopenssl: openssl modules'
    - 'python-dnspython: for dig lookup'
    - 'python-ovirt-engine-sdk: ovirt support'
    - 'python-boto3: aws_s3 module'
    - 'python-ldap: ldap support'
    - 'python-proxmoxer: proxmox modules'
    - 'python-openstacksdk: OpenStack module'
    - 'python-pynetbox: NetBox module'
    - 'python-ldap: LDAP modules'
    - 'python-kubernetes: Kubernetes modules'
    - 'python-keyring: Keyring module'
    - 'python-github3py: GitHub module'
    - 'python-lxc: LXC module'
    - 'python-fqdn: fqdn_valid module'
    - 'acme-tiny: openssl_certificate module'
  provides:
    - python-ansible_collections
  source:
    - https://pypi.python.org/packages/source/a/ansible/ansible-13.0.0.tar.gz
  sha512sums:
    - cb51acf6bfd909d828431612220fab277b2e42d88e90ad0b6aa3bb514a8caac475f4c3e2f7df39c07ef8c014ca6759d0b45e033a01654205cec083e7ff4ce06d
pkgname:
  - name: ansible
# generated with artixpkg 0.37.4-1-any
