[less]
# GitHub tags are first in "beta" stage before released for general use.
# Hence use the proper version from the homepage.
source = "regex"
url = "https://www.greenwoodsoftware.com/less/"
regex = 'The current released version is less-(\d+).'
