version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "Patch01-fd-passing-libmilter.patch",
    "Patch02-Allow-setting-local-CFLAGS-devtools-M4-UNIX-defines.patch",
    "Patch03-libmilter-Makefile-m4.patch",
    "site.config.m4",
]
SPDX-FileCopyrightText = "libmilter contributors"
SPDX-License-Identifier = "Sendmail-8.23"
